### ISSUE TITLE
Unable to remove approval of NFT using ERC standard calls

### ISSUE THREAD

**Issue by a-ridley** [hashgraph/hedera-smart-contracts#100]
### Description

**Background Info:** HIP-376 adds support for Approve/Allowance/transferFrom standard calls from ERC20 and ERC721. 
Speaking only to ERC721 approve standard call, it states that 'if the spender address is 0, this creates a CryptoDeleteAllowanceTransaction instead and removes any allowances previously approved on the token.' 

**Issue:** Currently cannot remove approval of an account for a specific NFT serial number by making the spender address 0 using the SDK and ERC-721 standard calls.

When approving an allowance for a specific NFT serial number with the spender address set to (0x0000000000000000000000000000000000000000) the following error is returned:

```    
super(props, `receipt for transaction ${props.transactionId.toString()} contained error status ${props.status.toString()}`);
    ^

ReceiptStatusError: receipt for transaction 0.0.48612048@1665691932.78526059 contained error status INVALID_SOLIDITY_ADDRESS
    at new ReceiptStatusError (/workspace/hedera-erc721-examples/node_modules/@hashgraph/sdk/lib/ReceiptStatusError.cjs:45:5)
    at TransactionReceiptQuery._mapStatusError (/workspace/hedera-erc721-examples/node_modules/@hashgraph/sdk/lib/transaction/TransactionReceiptQuery.cjs:326:12)
    at TransactionReceiptQuery.execute (/workspace/hedera-erc721-examples/node_modules/@hashgraph/sdk/lib/Executable.cjs:690:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TransactionResponse.getReceipt (/workspace/hedera-erc721-examples/node_modules/@hashgraph/sdk/lib/transaction/TransactionResponse.cjs:100:21)
    at async TransactionResponse.getRecord (/workspace/hedera-erc721-examples/node_modules/@hashgraph/sdk/lib/transaction/TransactionResponse.cjs:119:5) {
  status: Status { _code: 29 },
  ```

**Expected outcome:** The contract call is successful and the approval is removed.
  
The gitpod code example does the following:
 1. creates 3 accounts: Treasury, Alice, and Bob.
2. creates 5 NFTs
3. deploys a smart contract
6. Treasury grants Alice approval for the 5 NFTs successfully
7. Attempts to remove NFT allowance for all 5 NFTs by setting spender address to 0

### Steps to reproduce

1. Open the following gitpod snapshot: https://gitpod.io#snapshot/2f753f8e-76c9-4da4-96e6-f02a32dcef95
2. Enter your testnet credentials in the .env file
3. `npm run start`
4. Notice the following error in the terminal: `...contained error status INVALID_SOLIDITY_ADDRESS`

### Hedera network

testnet

### Version

v2.18

### Operating system

macOS

**Comment by Nana-EC** [comment]
As part of the resolution for this can we creates tickets to address the following
- [ ] Add test coverage in ERC 20 / ERC 721 under https://github.com/hashgraph/hedera-smart-contracts/tree/main/test/hts-precompile
- [ ] Add sdk-js and sdk-java example coverage

**Comment by georgi-l95** [comment]
I think I've found the issue, this is your code snippet, between line 123-126 in `index.ts`:
```
    const approveParams = new ContractFunctionParameters()
      .addAddress('0x0000000000000000000000000000000000000000')
      .addAddress(aliceAccId.toSolidityAddress())
      .addUint256(serialNum);
```
First parameter is token address, not spender. Please paste this snippet, try again and let us know:
```
    const approveParams = new ContractFunctionParameters()
      .addAddress(tokenIdInSolidityFormat)
      .addAddress('0x0000000000000000000000000000000000000000')
      .addUint256(serialNum);
```
Should be working, here is an example [transaction](https://hashscan.io/#/testnet/transaction/0.0.48617146-1665747110-494261882?t=1665747119.559636003) that produces `CRYPTO DELETE ALLOWANCE`

**Comment by a-ridley** [comment]
> I think I've found the issue, this is your code snippet, between line 123-126 in `index.ts`:
> 
> ```
>     const approveParams = new ContractFunctionParameters()
>       .addAddress('0x0000000000000000000000000000000000000000')
>       .addAddress(aliceAccId.toSolidityAddress())
>       .addUint256(serialNum);
> ```
> 
> First parameter is token address, not spender. Please paste this snippet, try again and let us know:
> 
> ```
>     const approveParams = new ContractFunctionParameters()
>       .addAddress(tokenIdInSolidityFormat)
>       .addAddress('0x0000000000000000000000000000000000000000')
>       .addUint256(serialNum);
> ```
> 
> Should be working, here is an example [transaction](https://hashscan.io/#/testnet/transaction/0.0.48617146-1665747110-494261882?t=1665747119.559636003) that produces `CRYPTO DELETE ALLOWANCE` child record

Whoops, looks like I did flip those. Thanks, this is working as expected and can be closed.

**Comment by Nana-EC** [comment]
Thanks @a-ridley and @georgi-l95
