### ISSUE TITLE
Add Repo Maintainers to CODEOWNERS file

### ISSUE THREAD

**Issue by andrewb1269** [hashgraph/hedera-smart-contracts#1068]
# Update CODEOWNERS to provide maintainers ownership of all files in their repos

**Description**:

Update this repositories `.github/CODEOWNER` file to ensure that the repository maintainer
group(s) have full control of the files in this repository.

**Comment by rbarkerSL** [comment]
I would recommend doing the following:

remove user `@attest08`. Add `@hashgraph/hedera-smart-contracts` to the catch-all
