### ISSUE TITLE
Unable to deploy Smart Contract on Mainnet (perfect on testnet)

### ISSUE THREAD

**Issue by Burstall** [hashgraph/hedera-smart-contracts#131]
### Description

[MinterContract.zip](https://github.com/hashgraph/hedera-smart-contracts/files/10049825/MinterContract.zip)

Trying to deploy the bytecode as compiled however the FileAppendTransaction() fails due to timeouts. Everything is smooth on testnet but deploying live is currently impossible.

- Uploading bytecode...
- The smart contract bytecode file ID is: 0.0.1448021
Error getting nodes from mirror for file 0.0.102 during attempt 0. Waiting 250 ms before next attempt: No connection established
Error getting nodes from mirror for file 0.0.102 during attempt 1. Waiting 500 ms before next attempt: No connection established
Error getting nodes from mirror for file 0.0.102 during attempt 2. Waiting 1000 ms before next attempt: No connection established
Error getting nodes from mirror for file 0.0.102 during attempt 3. Waiting 2000 ms before next attempt: No connection established
Error getting nodes from mirror for file 0.0.102 during attempt 4. Waiting 4000 ms before next attempt: No connection established
Error getting nodes from mirror for file 0.0.102 during attempt 5. Waiting 8000 ms before next attempt: No connection established
Error getting nodes from mirror for file 0.0.102 during attempt 6. Waiting 8000 ms before next attempt: No connection established
Error getting nodes from mirror for file 0.0.102 during attempt 7. Waiting 8000 ms before next attempt: No connection established
Error getting nodes from mirror for file 0.0.102 during attempt 8. Waiting 8000 ms before next attempt: No connection established
Error: max attempts of 20 was reached for request with last error being: TRANSACTION_EXPIRED
    at FileAppendTransaction.execute (C:\Users\signu\github\hedera-SC-minter\node_modules\@hashgraph\sdk\lib\Executable.cjs:699:11)
    at async FileAppendTransaction.executeAll (C:\Users\signu\github\hedera-SC-minter\node_modules\@hashgraph\sdk\lib\file\FileAppendTransaction.cjs:396:24)
    at async FileAppendTransaction.execute (C:\Users\signu\github\hedera-SC-minter\node_modules\@hashgraph\sdk\lib\file\FileAppendTransaction.cjs:365:13)
    at async loadBytecodeToHedera (C:\Users\signu\github\hedera-SC-minter\scripts\loadBytecodeHederaFS.js:39:27)
    at async main (C:\Users\signu\github\hedera-SC-minter\scripts\loadBytecodeHederaFS.js:97:3)

### Steps to reproduce

`async function loadBytecodeToHedera(bytecode) {
	// Create a file on Hedera and store the hex-encoded bytecode
	const fileCreateTx = new FileCreateTransaction().setKeys([operatorKey]);
	const fileSubmit = await fileCreateTx.execute(client);
	const fileCreateRx = await fileSubmit.getReceipt(client);
	const bytecodeFileId = fileCreateRx.fileId;
	console.log(`- The smart contract bytecode file ID is: ${bytecodeFileId}`);

	// Append contents to the file
	const fileAppendTx = new FileAppendTransaction()
		.setFileId(bytecodeFileId)
		.setContents(bytecode)
		.setMaxAttempts(20)
		.setMaxChunks(20)
		.setMaxTransactionFee(new Hbar(3));
	const fileAppendSubmit = await fileAppendTx.execute(client);
	const fileAppendRx = await fileAppendSubmit.getReceipt(client);
	console.log(`- Content added: ${fileAppendRx.status} \n`);

}`

run this with the previously attached compiled bytecode on mainnet (works fine on testnet). 

### Hedera network

mainnet

### Version

v0.30

**Comment by Burstall** [comment]
The issue comes in the FileAppendTransaction() auto chunking. I rebuilt a script to slice the bytecode and upload one chunk at a time and it was fine. At least I have a solution.

**Comment by Burstall** [comment]
So I got to be able to deploy the contract as above but I can't use the contract effectively as it falls over in what looks like the same manner when I request the transaction record. I have tried a time buffer and it fails regularly within the first dozen calls (I am uploading data to the contract for an NFT mint on loop). I am not calling the mirror node myself directly so I can only assume this is something under the covers. Disappointing that mainnet and testnet seem to behave differently on basic behaviour. 

`
Error getting nodes from mirror for file 0.0.102 during attempt 0. Waiting 250 ms before next attempt: No connection established
Error getting nodes from mirror for file 0.0.102 during attempt 1. Waiting 500 ms before next attempt: No connection established
Error getting nodes from mirror for file 0.0.102 during attempt 2. Waiting 1000 ms before next attempt: No connection established
Error: max attempts of 10 was reached for request with last error being: UNKNOWN
    at TransactionReceiptQuery.execute (C:\Users\signu\github\hedera-SC-minter\node_modules\@hashgraph\sdk\lib\Executable.cjs:699:11)
    at async TransactionResponse.getReceipt (C:\Users\signu\github\hedera-SC-minter\node_modules\@hashgraph\sdk\lib\transaction\TransactionResponse.cjs:100:21)
    at async TransactionResponse.getRecord (C:\Users\signu\github\hedera-SC-minter\node_modules\@hashgraph\sdk\lib\transaction\TransactionResponse.cjs:119:5)
    at async contractExecuteFcn (C:\Users\signu\github\hedera-SC-minter\scripts\prepareMinter.js:424:17)
    at async useSetterStringArray (C:\Users\signu\github\hedera-SC-minter\scripts\prepareMinter.js:399:43)
    at async uploadMetadata (C:\Users\signu\github\hedera-SC-minter\scripts\prepareMinter.js:383:16)
    at async main (C:\Users\signu\github\hedera-SC-minter\scripts\prepareMinter.js:148:4)
`

**Comment by Kalina-Todorova** [comment]
Hi @Burstall we will look into this, could you share which version of the js sdk you are using?

**Comment by Burstall** [comment]
2.18.3 (another project member tried and was using 2.18.6 I believe with the same issues)

**Comment by ochikov** [comment]
Hello @Burstall,
We catch what causes the first error:  `Error getting nodes from mirror for file 0.0.102 during attempt`
We are going to release a new version soon with the fix. You can get rid of it by manually setting the mirror node for MAINNET as the following:
`
 client.setMirrorNetwork("mainnet-public.mirrornode.hedera.com:443");

`

Then I removed the `.setMaxTransactionFee(new Hbar(3));` because I was not able to deploy the contract with such minor fee. On my side browsing the Hashscan, it takes me 14 file appends. 

I was able to get the `- Content added: SUCCESS ` message.

**Comment by Burstall** [comment]
good to know the workaround and what to look for in the future. thanks.
