### ISSUE TITLE
Create end to end tests for atomic crypto transfer

### ISSUE THREAD

**Issue by lukelee-sl** [hashgraph/hedera-smart-contracts#132]
### Problem

Tests are needed to exercise the atomic crypto transfer functionality

### Solution

Write tests that show:
- basic transfers of hbars, fungible and non-fungible tokens in various combinations.
- write negative tests to show transfer failure when approval and allowance are not present.
- write negative tests to show transfer failure when keys are not present.
Additional test as enumerated in this [issue](https://github.com/hashgraph/hedera-services/issues/4089)

**Comment by Nana-EC** [comment]
@quiet-node to connect the existing work and close ticket if fully resolved

**Comment by quiet-node** [comment]
Closing as finished resolved in https://github.com/hashgraph/hedera-smart-contracts/pull/800
