### ISSUE TITLE
Unclear if `mintToken` supports minting multiple NFTs

### ISSUE THREAD

**Issue by Shungy** [hashgraph/hedera-smart-contracts#144]
## Lines of Code

https://github.com/hashgraph/hedera-smart-contracts/blob/d7762ee23116fb1a389ddbcc50e7113c9565b92c/contracts/hts-precompile/HederaTokenService.sol#L47-L68

## Description

`metadata` argument and `serialNumbers` return value of `mintToken()` function are arrays, which imply the ability to mint multiple NFTs at once. However `amount` argument only accepts `0` for minting NFTs as seen from [the NatSpec comment](https://github.com/hashgraph/hedera-smart-contracts/blob/d7762ee23116fb1a389ddbcc50e7113c9565b92c/contracts/hts-precompile/HederaTokenService.sol#L50) and [the unit tests](https://github.com/hashgraph/hedera-smart-contracts/blob/d7762ee23116fb1a389ddbcc50e7113c9565b92c/test/hts-precompile/token-create/tokenCreateContract.js#L124).

## Recommendation

Either expect `amount` to be equal or greater than `1`, or make `metadata` and `serialNumbers` non-arrays.

**Comment by natanasow** [comment]
@Shungy you can mint multiple NFTs at once by passing the numerous metadata
```typescript
const tx = await tokenCreateContract.mintTokenPublic(nftTokenAddress, 0, ['0x02', '0x03', '0x04'], {
      gasLimit: 1_000_000
  });

const { serialNumbers } = (await tx.wait()).events.filter(e => e.event === 'MintedToken')[0].args;
// serialNumbers
// [
//     BigNumber { value: "1" },
//     BigNumber { value: "2" },
//     BigNumber { value: "3" }
// ]
```
The `amount` value is used only for Fungible Tokens, [it's skipped (passing zero)](https://github.com/hashgraph/hedera-smart-contracts/blob/main/contracts/hts-precompile/HederaTokenService.sol#L50) for Non-Fungible Tokens.

**Comment by Shungy** [comment]
Ah I see. Thanks for the response.
