### ISSUE TITLE
Add solidity and ABI files for redirectForToken()

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#150]
### Problem

The consensus nodes supports the system contract function `redirectForToken()` - `0x618dc65e`, which per HIP 218 is a simple proxy redirect that allows solidity contracts to interact with each tokens as though they were accounts with code.
However, this function is not present in the smart contract repo and therefore has no ABI file to support decoding of function selectors

### Solution

Add an interface contract under `https://github.com/hashgraph/hedera-smart-contracts/tree/main/contracts/hts-precompile` that exposes the `redirectForToken()` function and maps to the `0x618dc65e` selector

**Comment by stoqnkpL** [comment]
Function selector: 0x618dc65e 
Function signature: redirectForToken(address token, bytes memory data)
data: the function selector from the ERC interface + the bytes input for the function called

Example:
- Someone wants to call [balanceOf(address) from ERC20](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/3d7a93876a2e5e1d7fe29b5a0e96e222afdc4cfa/contracts/token/ERC20/IERC20.sol#L32)
- He would make a call to ERC20(<HTS token address>).balanceOf(address)
- Under the hood, services would replace the call with a call to the HTS system contract:
address(0x167).redirectForToken(<HTS token address>, encodeWithSelector(balanceOf(address))
