### ISSUE TITLE
UpdateTokenInfo in HTS precompile removes memo content

### ISSUE THREAD

**Issue by AlbertoMolinaIoBuilders** [hashgraph/hedera-smart-contracts#185]
### Description

We are updating Tokens using the HTS precompiled (0x167), more precisely, invoking the method **updateTokenInfo**, our goal is to update the Token's keys and the treasury account, this is our code

`
IHederaTokenService.HederaToken memory hederaTokenInfo;
hederaTokenInfo.tokenKeys = hederaKeys;
if (newTreasury != address(0)) hederaTokenInfo.treasury = newTreasury;
int64 responseCode = IHederaTokenService(_PRECOMPILED_ADDRESS)
.updateTokenInfo(currentTokenAddress, hederaTokenInfo);
_checkResponse(responseCode);
`

Keys and Treasury account get properly updated (as expected) but apparently the **memo** content get's deleted...
We have tested it on token **0.0.3705424** in TestNet.

### Steps to reproduce

- Create a token with a non-empty memo
- Update the Token Info through the HTS precompiled (_updateTokenInfo_ method, passing a _HederaToken_ struct with an _empty memo_ and _non empty Keys/Treasury_)
- Check that the memo field has been cleared

### Hedera network

testnet

### Version

latest

### Operating system

None

**Comment by georgi-l95** [comment]
Hey @AlbertoMolinaIoBuilders , thanks for logging this issue, we've opened a issue in the services repo to fix this. As soon as it fixed, we'll let you know here .

**Comment by georgi-l95** [comment]
Hey @AlbertoMolinaIoBuilders , this issue is resolved. Fix is on previewnet and local-node currently. Can you try and get back to us if you still experience this ?

**Comment by Kalina-Todorova** [comment]
Hi @AlbertoMolinaIoBuilders closing this issue as we have verified the fix. Please feel free to reach out if you face further issues.

**Comment by AlbertoMolinaIoBuilders** [comment]
Hello,
sorr for the delay, we just tested in previewnet and it looks like memo is still been removed for the token is updated....
this is the token we used for testing in case you need it (0.0.69321)

**Comment by Nana-EC** [comment]
@AlbertoMolinaIoBuilders seems the issue was resolved in 0.38
Closing this as such.
Please notify if for some reason you observe otherwise
