### ISSUE TITLE
Token's custom fractional fee without a minimum amount is unretrievable 

### ISSUE THREAD

**Issue by psychoter** [hashgraph/hedera-smart-contracts#244]
### Description

I tried to retrieve some token's custom fee rules within my smart contract, and there were no problem until I encounter a case where the token had a fractional fee. first I thought every fractional fees are excluded, but it seems like it only happens with those without a minimum amount.

### Steps to reproduce

(IHederaTokenService.FixedFee[] memory fixedFees, IHederaTokenService.FractionalFee[] memory fractionalFees,) = SafeHTS.safeGetTokenCustomFees(token);

fractionalFees.length // => returns 0 while the token has a fractional rule

### Additional context

token ID: **0.0.14021429**

### Hedera network

testnet

### Version

-

### Operating system

None

**Comment by natanasow** [comment]
@psychoter Hello, [the fix](https://github.com/hashgraph/hedera-services/pull/7028) is already done in services and will be included in the 0.40 release.

**Comment by psychoter** [comment]
> @psychoter Hello, [the fix](https://github.com/hashgraph/hedera-services/pull/7028) is already done in services and will be included in the 0.40 release.

Happy to hear that, I really appreciate it.
