### ISSUE TITLE
Update tests to handle new gas values.

### ISSUE THREAD

**Issue by ebadiere** [hashgraph/hedera-smart-contracts#249]
### Description

Tests are failing with messages like:
```
Transaction gas limit provided '21000' is insufficient of intrinsic gas required '23176'
```

### Steps to reproduce

Run the tests in CI.  This was discovered while cutting a release.

### Hedera network

other

### Version

v.0.4.0

### Operating system

macOS

**Comment by quiet-node** [comment]
Closing as fixed
