### ISSUE TITLE
Update smart contract repo with interfaces

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hedera-smart-contracts#44]
### Problem

Add new interfaces from HIP-514 to the smart contract repo

### Solution

Add interfaces

**Comment by Nana-EC** [comment]
@Kalina-Todorova [IHederaTokenService.sol](https://github.com/hashgraph/hedera-smart-contracts/blob/main/hts-precompile/IHederaTokenService.sol) was already updated.
Is this a no-op or referring to something else.

**Comment by Nana-EC** [comment]
Closing as covered by #34
