### ISSUE TITLE
[Solidity Support] Address operations

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#445]
### Problem

The Hedera network supports solidity as one of the smart contracts development languages.
Occasionally items have shown up that surfaced in-equivalence at the language layer.

### Solution

Add support for address operations

- Add a /contracts/solidity/address folder
- Cover the tasklist below

```[tasklist]
### Transaction property Tasks
- [x] `<address>.balance(uint256)`
- [x] `<address>.code(bytes memory)`
- [x] `<address>.codehash(bytes32)`
- [x] `<address payable>.transfer(uint256 amount)`
- [x] `<address payable>.send(uint256 amount) returns (bool)`
- [x] `<address>.call(bytes memory) returns (bool, bytes memory)`
- [x] `<address>.delegatecall(bytes memory) returns (bool, bytes memory)`
- [x] `<address>.staticcall(bytes memory) returns (bool, bytes memory)`
```

 Ref: https://docs.soliditylang.org/en/latest/units-and-global-variables.html

**Comment by BrightTNut** [comment]
can i write code for this

**Comment by Nana-EC** [comment]
Thanks @BrightTNut 
Great suggestions.
We're hoping to get through the ones you mentioned and more.

I'm not clear on your question but yes you should be able to write the code you noted in your smart contracts, if there are bugs you encounter please feel free to open an issue and or PR to bring it to our attention so it may be addressed. 
As noted though we'll be adding examples with tests for this also.

Thanks

**Comment by Nana-EC** [comment]
FYI opened https://github.com/hashgraph/hedera-smart-contracts/issues/459
As noted more tickets for coverage will be opened.
Please let us know if there are any other issues or interests in solidity behaviour you encounter.
