### ISSUE TITLE
[Solidity Support] Defaults values

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#471]
### Problem

The Hedera network supports solidity as one of the smart contracts development languages.
Occasionally items have shown up that surfaced in-equivalence at the language layer.

### Solution

Add examples for assembly address operations

- Add `/contracts/solidity/defaults`
- Cover the tasklist below to read default values

```[tasklist]
### Defaults Tasks
- [x] `uint<M>` cover different variations
- [x] `int<M>` cover different variations
- [ ] `fixed<M>x<N>`  cover different variations
- [ ] `unfixed<M>x<N>`  cover different variations
- [x] `bytes<M>`
- [x] `string`
- [x] `<type>[]`
- [x] `address`
- [x] `mapping`
```

Declare variable and read to verify default values

**Comment by stefan-stefanooov** [comment]
As far as I understand the "fixed" type is still not fully supported in Solidity.
