### ISSUE TITLE
[Solidity Support] Panic Errors

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#483]
### Problem

The Hedera network supports solidity as one of the smart contracts development languages.
Occasionally items have shown up that surfaced in-equivalence at the language layer.

### Solution

Add examples for panic errors operations

- Add `/contracts/solidity/errors/Panic.sol`
- Cover the tasklist below for 10 panic variations `0x00` to `0x51` . See https://docs.soliditylang.org/en/latest/control-structures.html#panic-via-assert-and-error-via-require 

```[tasklist]
### Panic Error Tasks
- [x] `0x00` Used for generic compiler inserted panics.
- [x] 0x01: If you call assert with an argument that evaluates to false.
- [x] 0x11: If an arithmetic operation results in underflow or overflow outside of an unchecked { ... } block.
- [x] 0x12; If you divide or modulo by zero (e.g. 5 / 0 or 23 % 0).a
- [x] 0x21: If you convert a value that is too big or negative into an enum type.
- [ ] 0x22: If you access a storage byte array that is incorrectly encoded.
- [ ] 0x31: If you call .pop() on an empty array.
- [x] 0x32: If you access an array, bytesN or an array slice at an out-of-bounds or negative index (i.e. x[i] where i >= x.length or i < 0).
- [x] 0x41: If you allocate too much memory or create an array that is too large.
- [x] 0x51: If you call a zero-initialized variable of internal function type.
```

**Comment by konstantinabl** [comment]
@Nana-EC Hey Nana, not sure how to produce a test for 0x22.

**Comment by konstantinabl** [comment]
After a discussion with @Nana-EC  and @shemnon it was decided that a test for 0x22 panic error could be skipped because it would account for thing that were already tested. Also we are not a project that uses Solidity as an inflection point and such test won't bring much value
