### ISSUE TITLE
Import Relay BaseHTS as TokenManagementContract

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#52]
### Problem

The relay repo added a [BaseHTS.sol](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/server/tests/contracts/BaseHTS.sol) contract that was helpful as an example that uses the wrapper contract for HIP 514 features.
This repo has no such wrapper contract with details

### Solution

Copy over the [logic](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/server/tests/contracts/BaseHTS.sol) into a `TokenManagementContract.sol` file

**Comment by georgi-l95** [comment]
All functions from relay wrapper contract have been transferred in this repo, with this PR #74
