### ISSUE TITLE
HTS NFT is still not compatible with Metamask.

### ISSUE THREAD

**Issue by yonac1** [hashgraph/hedera-smart-contracts#634]
### Description

HTS NFT is still not compatible with Metamask. I'm trying to send an NFT through HTS to a Hedera Testnet Metamask wallet, but then the NFT shows it to me as a Token in the token list tab inside Metamask instead of under the "NFTs" Tab and it says in the MetaMask "No NFTs yet"
I already associated the nft token id
<img width="405" alt="2023-12-14_-17 29 29" src="https://github.com/hashgraph/hedera-smart-contracts/assets/81573021/0211a6cf-7e8e-478d-aefd-1bad1cdfae83">
<img width="400" alt="2023-12-14_-17 31 11" src="https://github.com/hashgraph/hedera-smart-contracts/assets/81573021/c9d602dd-f2d5-4ef4-abd2-a5106cefca96">

### Steps to reproduce

1. send an NFT through HTS to a Hedera Testnet Metamask wallet.
2. NFT shows it to me as a Token in the token list tab inside Metamask instead of under the "NFTs" Tab.

### Hedera network

testnet

### Version

v2.25.0

### Operating system

Linux

**Comment by Nana-EC** [comment]
Thanks @yonac1 for the ticket.
We'll take a look and circle back.

Could you aid troubleshooting by providing your token id on tesnet.
Thanks

**Comment by AlfredoG87** [comment]
@yonac1 how did you add the NFT Token to MetaMask?

Did it auto appear? did you used Hashscan to associate and add token?

I ask, since I was able to add an NFT Token manually using MetaMask, however when doing it trough HashScan, it indeed was added on the ERC-20 Section.



![Image](https://github.com/hashgraph/hedera-smart-contracts/assets/123040664/4d579873-81af-449a-9523-370f225e1799)

**Comment by AlfredoG87** [comment]
@Nana-EC this seems to be an "issue" with Hashcan and how is it adding tokens to Metamask, when adding tokens to metamask, is done using the method `wallet_watchAsset` and params, see example:
```
      type: 'ERC721', // Initially, this method only supports ERC-721 tokens
      options: {
        address: tokenAddress, // The address that the token is at.
        symbol: tokenSymbol, // A ticker symbol or shorthand, up to 5 chars.
        decimals: tokenDecimals, // The number of decimals in the token
        image: tokenImage, // A string url of the token logo
      },
```

But taking a look at the hashscan explorer, it looks like is sending always `ERC20` on the `type` field of the params.

see [here](https://github.com/hashgraph/hedera-mirror-node-explorer/blob/f7b86e2edb3e7cde6aae2da09cc7bb5b89203877/src/utils/wallet/WalletDriver_Ethereum.ts#L51).

**Comment by yonac1** [comment]
> Thanks @yonac1 for the ticket. We'll take a look and circle back.
> 
> Could you aid troubleshooting by providing your token id on tesnet. Thanks

Yes it is: 0.0.6751279

**Comment by yonac1** [comment]
> @yonac1 how did you add the NFT Token to MetaMask?
> 
> Did it auto appear? did you used Hashscan to associate and add token?
> 
> I ask, since I was able to add an NFT Token manually using MetaMask, however when doing it trough HashScan, it indeed was added on the ERC-20 Section.
> 
> ![Image](https://private-user-images.githubusercontent.com/123040664/298228022-4d579873-81af-449a-9523-370f225e1799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMDU4OTcsIm5iZiI6MTcwNjAwNTU5NywicGF0aCI6Ii8xMjMwNDA2NjQvMjk4MjI4MDIyLTRkNTc5ODczLTgxYWYtNDQ5YS05NTIzLTM3MGYyMjVlMTc5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxMDI2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMmI2ZmJlMTE3YTBiOWJiMzNlNWQwZjYxNDdmNWMxNWIwMGEzOTQ0YjczYWFkMzc3ZDUwNTE3YzA0N2QzMjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kN_jY18izkROZWZoqs688Gyfyzddbim7vsxU-Zm07Jg)

I had to add it manually, it shown on my balance that I have 1 PBL on HashScan even though It's an NFT, I want to see it in the NFT Tab, I associate the token with ethers like this: 

`const provider = new ethers.providers.Web3Provider(window.ethereum, "any");
    const signer = provider.getSigner();
    const abi = [`function associate()`, `function dissociate()`];
    const nftAddress =
      "0x" +
      TokenId.fromString(process.env.REACT_APP_NFT_TOKEN_ID)
        .toSolidityAddress()
        .toString();
    let txHash;
    const gasLimit = ASSOCIATE_GAS_LIMIT;

    const myContract = new ethers.Contract(nftAddress, abi, signer);
    const associateTx = await myContract.associate({ gasLimit: gasLimit });
    const associateRx = await associateTx.wait();
    txHash = associateRx.transactionHash;`

When sending it to a metamask wallet which associate it in that way it doesn't get into the NFT Tab

**Comment by yonac1** [comment]
@AlfredoG87 this is what happen when i'm try to import the NFT 
<img width="1710" alt="image" src="https://github.com/hashgraph/hedera-smart-contracts/assets/81573021/3e57f05b-1278-43ed-ae23-323f57deda25">

**Comment by quiet-node** [comment]
Hello @yonac1, we appreciate your time and effort to open up this ticket, and sorry for this late response! Good thing this will now be my main priority.

> it shown on my balance that I have 1 PBL on HashScan even though It's an NFT

On Hashscan, specifically on the Account Detail page, `balances` is the section where all your tokens (both fungible and non-fungible) are displayed. The balance displayed on HashScan showing "1 PBL" indicating ownership of 1 token with the symbol PBL. By clicking on the 'PBL' symbol, you'll be directed to the Token Detail page, where you can learn more about the token, including its type (non-fungible in this case), keys, expiration, and other details.

> I associate the token with ethers like this:

> const provider = new ethers.providers.Web3Provider(window.ethereum, "any"); const signer = provider.getSigner(); 

> const abi = [function associate(), function dissociate()`];

> const nftAddress =
> "0x" +
> TokenId.fromString(process.env.REACT_APP_NFT_TOKEN_ID)
> .toSolidityAddress()
> .toString();

> let txHash;

> const gasLimit = ASSOCIATE_GAS_LIMIT;

>const myContract = new ethers.Contract(nftAddress, abi, signer);

>const associateTx = await myContract.associate({ gasLimit: gasLimit });

>const associateRx = await associateTx.wait();

>txHash = associateRx.transactionHash;`

Excellent! That's exactly how you associate a token using the [HIP-719](https://hips.hedera.com/hip/hip-719). However, we have good news – manual token association is no longer necessary. HashScan now allows users to connect their wallet directly to the platform, enabling them to associate and add the token to Metamask effortlessly.

For your specific case, follow these steps:

1. Click on the 'Connect wallet...' button in the top right corner.
2. Choose Metamask as the wallet provider.
3. Click 'Connect' and switch the wallet to the current network (testnet in this case).
4. Choose the right account to connect.

After connecting, you'll notice a button labeled 'Import to Metamask' next to the token address within the Token Detail page. It will look like this image
<img width="741" alt="image" src="https://github.com/hashgraph/hedera-smart-contracts/assets/66233296/d61af2cb-b533-4aaa-934d-2dce6b90afd6">

Click on this button, and it will prompt you to associate the token with the connected account. Additionally, it will ask if you want to add the token to Metamask.

As Fredy has mentioned about [this issue above](https://github.com/hashgraph/hedera-smart-contracts/issues/634#issuecomment-1901304615), by clicking the `Import to Metamask` button, it will only add that token to the `Tokens` tab but not NFTs. I will create a ticket on Hashscan and push in the fix soon.

> this is what happen when i'm try to import the NFT <img alt="image" width="1710" src="https://private-user-images.githubusercontent.com/81573021/298904827-3e57f05b-1278-43ed-ae23-323f57deda25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjQwODcsIm5iZiI6MTcwNjgyMzc4NywicGF0aCI6Ii84MTU3MzAyMS8yOTg5MDQ4MjctM2U1N2YwNWItMTI3OC00M2VkLWFlMjMtMzIzZjU3ZGVkYTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDIxNDMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZTkzNjcwYWE2Mjk1ODcwNTI5MTg5NDQ1ZmQzOGM2NWI1Y2U5YTZhOTljMjdkMzNlOTE4YjU1YTgwMjIwOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pO3GLczKtFcYlvps_QWNf16k1j1C8xlazI1bbaN-Eyc">

I notice you're attempting to manually add the NFT to your Metamask. However, based on the provided picture, it seems there might be confusion between the Token ID and Token Address. Let me clarify:

The Token ID represents the unique identifier (or Serial Number in HTS) of the specific token you own. Follow these steps to find the Token ID for your owned token:

1. Visit your Account Detail page on Hashscan.
2. In the 'Balances' section, locate the 'Show all tokens' button. Clicking it will redirect you to the 'Account Balances' page, displaying all fungible and non-fungible tokens you own.
3. Identify the token you want to check for the Serial Number, and click on it. This will lead you to the account collections page, where you can find the Serial Number associated with that token.
4. Now, in Metamask, go to the NFTs tab and click on 'Import NFT.'
5. Input the token address in the 'Address' text box and the Serial Number you just found in the 'Token ID' text box.
6. Click 'Import,' and you'll see your NFT successfully imported into Metamask.

If you still have any question, please don't hesitate to ask!

P.S. Our Testnet recently underwent quarterly maintenance, resulting in a complete reset of the entire Testnet network. All tokens have been wiped off, and all accounts have been updated with new account IDs and keys. We recommend revisiting your Hedera Portal to review and verify your account information.

**Comment by yonac1** [comment]
Thanks for the answer @quiet-node , quick question, In Hedera Mainnet, are the users will have to also import manually the NFT as you mentioned or it will automatically will be in their NFT Tab inside the metamask wallet just like on HashPack or on Ethereum Network on Metamask. and if it manually, are you doing something about it? Customers that using Hedera Metamask inside our dapp can't see their NFT on their wallet Tab as I mentioned.

**Comment by quiet-node** [comment]
Hi @yonac1, appreciate your prompt response! Currently, within the Hedera ecosystem, the only automated method for importing tokens into Metamask is through Hashscan.io. Presently, this process is designed exclusively for `ERC20` tokens, leading Hashscan to incorrectly categorize NFTs as fungible assets in your wallet. I've documented this issue in a [new ticket](https://github.com/hashgraph/hedera-mirror-node-explorer/issues/889) on Hashscan. I'm actively collaborating with the Hashscan team to address this, and the fix will be implemented soon. Once resolved, you and your DApp users won't need to manually import tokens; they can simply visit Hashscan to accomplish this.

Moreover, your team has the option to incorporate a similar `importing tokens` flow directly within your DApp using Metamask's `wallet_watchasset` feature. For more details, please refer to the [official documentation](https://docs.metamask.io/wallet/reference/wallet_watchasset/). If your team finds this approach appealing, it offers an additional avenue for a seamless token import experience.

**Comment by yonac1** [comment]
@quiet-node Thank you very much! will be able to attach the Hashscan addressed GitHub Issue?

**Comment by yonac1** [comment]
@quiet-node Thank You Very Much!

**Comment by quiet-node** [comment]
@yonac1 you're very welcome! We are working on this problem and we will push in the fix soon!

**Comment by quiet-node** [comment]
Hello @yonac1, in [this PR](https://github.com/hashgraph/hedera-mirror-node-explorer/pull/898) the mirror-node-explorer team and I have successfully fix this bug. You can now associate, dissociate tokens (fungible and non-fungible). You can also import the tokens into your wallets. A couple of notes:
- Token import only natively support on Metamask, Coinbase, and Brave wallet
- Only Metamask natively support importing ERC-721 standard (NFT) tokens.

Again, thanks for your time opening this ticket! Please feel free to let me know if you have any questions!
