### ISSUE TITLE
Add proxy upgrade contract example w HTS

### ISSUE THREAD

**Issue by Nana-EC** [hashgraph/hedera-smart-contracts#84]
### Problem

Hedera is able to support upgradeable contracts using the proxy method.
However, no example exists in this repo yet

### Solution

Add 
- a set of contracts example under `contracts/proxy-upgrade` that showcase how an upgradeable contract may be utilized w HTS logic e.g. very simple DEX ref.
- unit tests that show valid contract execution
- [Stretch] manual upgrade flow in a test that verifies eventual updated logic

Note there may be some dev tool limitations due to CREATE 1 logic by Hedera vs Ethereum but this should either have documentation or a work around provided.

**Comment by georgi-l95** [comment]
Blocked by https://github.com/hashgraph/hedera-json-rpc-relay/issues/703
