### ISSUE TITLE
Invalid type for amount in `wipeTokenAccount` function argument

### ISSUE THREAD

**Issue by Shungy** [hashgraph/hedera-smart-contracts#85]
https://github.com/hashgraph/hedera-smart-contracts/blob/30404a3f1ed06031558c343ea1f12391f1d60d0a/contracts/hts-precompile/HederaTokenService.sol#L520

It should be uint64, not uint32.

**Comment by Nana-EC** [comment]
@georgi-l95 let's see if this impacts https://github.com/hashgraph/hedera-smart-contracts/pull/99

**Comment by georgi-l95** [comment]
It makes sense to be uint64 and maybe we should change it with PR #99 from uint32 to int64, but that means that we have to change it [in services](https://github.com/hashgraph/hedera-services/pull/4067) and in [docs](https://hips.hedera.com/hip/hip-514) as well.

**Comment by georgi-l95** [comment]
Resolved in services repo. Will be resolved here as well in PR #99 .

**Comment by georgi-l95** [comment]
Fixed in #151
