### ISSUE TITLE
Add tests for calling isAssociated() via HRC proxy contract

### ISSUE THREAD

**Issue by georgi-l95** [hashgraph/hedera-smart-contracts#861]
### Problem

Until recently calling isAssociated() was not possible, but now with the resolving of [this](https://github.com/hashgraph/hedera-services/issues/5950) issue in services, this is possible.

### Solution

We'd need to extend our current examples to support and test this behaviour.

**Comment by Ivo-Yankov** [comment]
Тhis issue is blocked for now. The `isAssociated` method is a `view` type. This means that whenever it is called it would go through `eth_call`, which in turn will execute the method in the web3 module of the Mirror node. But the EVM of the mirror node is not yet updated with the opcode for this method.

**Comment by Ivo-Yankov** [comment]
This can be unblocked sooner by this: https://github.com/hashgraph/hedera-json-rpc-relay/issues/2810
