### ISSUE TITLE
ci: [2024-Q3] CI/CD Audit Story

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/hedera-smart-contracts#872]
# CI/CD Repository Audit

**Description**:
Perform repository audit

# Administrative Audit Criteria

### Actions State
If actions have not been run in the previous 6 months they should be disabled:
- [ ] Actions are/have been disabled

If actions have run in the last 6 months then actions shall remain enabled:
- [x] Actions are enabled

### General Tab
- [x] Require contributors to sign off on web-based commits

#### Features Section:
- [x] Disable Wiki
  - If it is in use, leave Wiki enabled. If not in use, remove functionality (uncheck Wiki option). Should be disabled whenever possible.
- [x] Enable Issues
- [x] Enable Preserve this Repository
- [x] Enable Discussions
- [x] Enable Projects
  
#### Pull Requests Section:
- [x] Enable Allow Squash Merging
- [x] Enable Always suggest updating pull request branches
- [x] Enable Automatically delete head branches
 
#### Pushes Section:
- [x] Pushes: Limit how many branches and tags can be updated in a single push (Default # is 5)

### Collaborators and Teams Tab
- [x] Teams are assigned to the repository
- [x] Individual contributors that are part of assigned teams are removed from contributors list

### Branches Tab
- [x] Individual branch protections are turned off

### Tags Tab
- [x] Individual tag protections are turned off

### Rules/Rulesets Tab
- [x] The repository uses the current rulesets

### Actions Tab
**If actions are enabled**:
- [x] Dependabot is enabled on the repository
- [ ] Codecov is enabled on the repository

### Webhooks Tab
- [x] All webhooks present are needed and in use
- [x] Snyk is enabled on the repo (check to see if the webhook exists and is in use)

### Secrets and Variables Tab
- [x] GitHub secrets are employed to store sensitive data
- [x] Tokens are stored securely as GitHub Secrets

## App Integrations
- [x] Dependabot is configured to monitor all relevant ecosystems
  - npm
  - electron
  - github actions
  - etc.
- [x] Code Coverage Reporting - Configure codecov on the repository
- [ ] CodeQL is enabled on the repository

### Security Checks in Repo
- [x] Secrets Management
  - [x] No hardcoded secrets in the workflow files or code
  - [x] Secrets are referenced in CI via config files or environment variables
- [x] Executable Path Integrity
  - [x] Integrity checks for executables are implemented
    - integrity checks should use either checksums or cryptographic hashes for verification
  - [x] Checksums/hashes are verified during CI process to detect unauthorized changes
  - [x] Expected checksums/hashes are stored securely and referenced through the CI pipeline
- [ ] `npx playwright install deps` is used to install OS dependencies instead of `aptitude`

### Code Formatting
  - [x] NodeJS Projects use ESLint/Prettier formatting
  - [ ] Java Projects use Checkstyle/Spotless formatting

### Dependabot

- [x] dependabot.yml is up to date

### Workflow checks

- [x] Appropriate permissions are set within the github workflows
- [x] All steps are named
- [x] All workflow actions are using pinned commits
- [x] The Step-Security Hardened Security action is enabled on each workflow job
- [x] Ensure no hard-coded keys in workflows
  - [ ] Alert devops-ci administrative team if new github secrets are needed to resolve hard-coded keys

### Self Hosted Runners

- [x] The Repository is using the latitude runner group label for the `runs-on` stanza

### CODEOWNERS

- [x] `.github/CODEOWNERS` is valid and up-to-date

### Other

- [ ] *If Applicable*: Alert repository owners of software versions that are no longer supported
- [ ] *If Applicable*: Alert repository owners when software versions are within 3 months of losing support

---

## Repository Settings

- [x] Require contributors to sign off on web-based commits
- [x] Features: Issues
- [x] Features: Preserve this Repository
- [x] Features: Discussions
- [x] Features: Projects
- [x] Pull Requests: Allow Squash Merging
- [x] Pull Requests: Always suggest updating pull request branches
- [x] Pull Requests: Automatically delete head branches
- [x] Pushes: Limit how many branches and tags can be updated in a single push

---

## Acceptance Criteria

- [ ] All Audit Criteria have been met

**Comment by mishomihov00** [comment]
Non-administrative checks are done. @andrewb1269hg assigning over to you.

**Comment by andrewb1269hg** [comment]
Removed AlfredoG87, david-bakin-sl, ebadiere, quiet-node from the contributor list as they're included in the `hedera-smart-contracts` team.

Removed georgi-l95, Ivo-Yankov, konstantinabl, MiroslavGatsanoga, natanasow from the contributor list as they're included in the `limechain-hedera` team.

**Comment by andrewb1269hg** [comment]
Administrative items are cleaned up and complete.

Over to @mishomihov00 to close out PR #998 then close out this issue.
