### ISSUE TITLE
HIP-1010: Solidity reference definition

### ISSUE THREAD

**Issue by stoyanov-st** [hashgraph/hedera-smart-contracts#876]
Add the solidity references mentioned in [HIP-1010 design doc](https://github.com/hashgraph/hedera-services/pull/14205/commits)
and include end-user tests also covered in the design document.

**Comment by konstantinabl** [comment]
Waiting for this [issue](https://github.com/hashgraph/hedera-mirror-node/issues/9136) to be finished in order for tests to run correctly
