### ISSUE TITLE
freshdesk issue #3347 & #3348 - add team reminders

### ISSUE THREAD

**Issue by rbarkerSL** [hashgraph/hedera-smart-contracts#939]
Helpdesk Tickets:

- [ ] https://swirldslabs.freshdesk.com/a/tickets/3347
- [ ] https://swirldslabs.freshdesk.com/a/tickets/3348

Github allows for scheduled reminders per team - https://docs.github.com/en/organizations/organizing-members-into-teams/managing-scheduled-reminders-for-your-team#creating-a-scheduled-reminder-for-a-team

Enable scheduled reminders for the team in the following repos: 
 
- `hedera-smart-contracts-product` team
  - [x] hedera-json-rpc-relay
  - [x] hedera-smart-contracts
  - [x] hedera-the-graph
  - [x] hedera-sourcify  
- `hedera-smart-contracts-core` team
  - [x] hedera-services

Please set the following options:
- "Ignore drafts" - step 13
- "Require review requests" - step 14
- "Remind authors" - step 15
- "Ignore approved pull request" then click on "Ignore 2 or more approvals" - step 16

**Comment by andrewb1269hg** [comment]
@Nana-EC what channel would you like to send notifications in Slack to?

**Comment by andrewb1269hg** [comment]
hedera-smart-contracts-product would go to the [#eng-smart-contracts-product](https://swirldslabs.slack.com/archives/C07A80QJNEA) (eng-smart-contracts-product) channel.
hedera-smart-contracts-core would go to the [#eng-smart-contracts-core](https://swirldslabs.slack.com/archives/C07ABN22BLM) (eng-smart-contracts-core) channel.

**Comment by andrewb1269hg** [comment]
Notifications have been set up for weekdays to the above teams on the listed repos.
