### ISSUE TITLE
Some of the readmes in here are out-of-date - we've reorganized the repo layout and forgotten to update them.

### ISSUE THREAD

**Issue by david-bakin-sl** [hashgraph/hedera-smart-contracts#967]
I was just looking around and found that:

* main repo readme has a link for "HTS Precompile methods" that's a 404.

    ![image](https://github.com/user-attachments/assets/91ec48cf-7ab7-4df3-b46a-67f47e545d8f)

* the contracts subdirectory has a readme which names several subdirectories that don't exist there, they've been moved elsewhere:

    ![image](https://github.com/user-attachments/assets/0d05c72f-7bd4-4478-a303-f744d2484079)

Likely other links are bad too, I haven't checked.

**Comment by quiet-node** [comment]
addressed in this PR https://github.com/hashgraph/hedera-smart-contracts/pull/966
